### PR TITLE
Add more unit_tests to the `Orderbook` class.

### PR DESCRIPTION
**Pull request by prathikanand7**
Hi @Tzadiko,

I have created a PR having `OrderbookTests` fixture. It tests whether all the orders are added, matched, modified and removed correctly within the `Orderbook`.

Regards,
Prathik

### CODE REVIEW

**Comment by Tzadiko** [comment]
Thanks for your enthusiasm in adding tests. All these test cases are covered in `test.cpp`. If there are cases that aren't covered, please follow the format in that file. In other words, add a file to `INSTANTIATE_TEST_CASE_P`

**Comment by prathikanand7** [comment]
okay..I shall try to do that.

**Comment by prathikanand7** [comment]
Hi @Tzadiko,

I spent some time yesterday and today and I have done some house-cleaning work on `test.cpp` along with adding 7 more test files. Here's a gist of work that I have done on this PR:

1. Added 7 more test files and along with that, Applied Google formatter. (if you're not happy with the formatted file, lmk, I can keep the way it was before)
2. Added `const` on local variables wherever it was missing, made all functions `static` inside the struct `InputHandler`
3. Added `contexpr` to `InputHandler handler` object inside parameterized test fixture.

Tests works fine. If any case is repetitive lmk. Let me know your thoughts. Cheers.

**Comment by Tzadiko** [comment]
Hey, sorry for the delay. It's hard to tell what changed given the inclusion of the Google formatting. Please revert that so I can better see the changeset.

**Comment by prathikanand7** [comment]
Hi Tomer @Tzadiko , 

sorry got busy with other stuffs. I have updated the PR, keeping only the relevant changes in `test.cpp` - removed the Google formatting. Please have a look, whenever you get some free time. Cheers for the new Gov! 👍

**Comment by prathikanand7** [comment]
Hey @Tzadiko , whenever you get time...if you can review the work, that would be awesome! cheers.

**Comment by prathikanand7** [comment]
Hey @Tzadiko, can you help me add these changes to your repo. It would mean a lot to me as a developer

**Comment by prathikanand7** [comment]
Hello @Tzadiko 🥲!

**Comment by Tzadiko** [comment]
I don't think this MR adds much value given the current change set. Just adding const somewhere and then adding constexpr to a class that has no constexpr methods doesn't change much. Most of the tests you've added are already covered. Thanks for your contribution. In the future, please refrain from continuosly commenting on someone's MR if they don't respond.

**Comment by prathikanand7** [comment]
I think, adding the `const` perfectly makes sense and makes the code more robust, maybe constexpr doesn't add much value. Also, the test cases added are not covered. For example, you don't have a test case that tests Large orders. Similarly, many others.

**Pull request closed without merging**
